apiVersion: v2
name: messenger
description: Open-source front-end part of messenger by team113.
version: 0.0.0-edge
appVersion: "0.1.0-alpha.5"
type: application
sources:
  - https://github.com/team113/messenger
annotations:
  artifacthub.io/license: AGPL-3.0-or-later
