apiVersion: v1
entries:
  messenger:
  - annotations:
      artifacthub.io/license: AGPL-3.0-or-later
    apiVersion: v2
    appVersion: 0.6.13
    created: "2026-01-20T22:06:20.246738573Z"
    description: Open-source front-end part of messenger by team113.
    digest: b2d532a7b50137ea58ff11e0011de2752bf61f7f7b6d8f103205e0e39a9f9d61
    name: messenger
    sources:
    - https://github.com/team113/messenger
    type: application
    urls:
    - https://team113.github.io/messenger/helm/messenger-0.2.0.tgz
    version: 0.2.0
  - annotations:
      artifacthub.io/license: AGPL-3.0-or-later
    apiVersion: v2
    appVersion: 0.6.1
    created: "2026-01-20T22:06:20.245959126Z"
    description: Open-source front-end part of messenger by team113.
    digest: 4cf58e31c171b62d678a45cdb91fa7b795271fe557f37b12360500ce39b53626
    name: messenger
    sources:
    - https://github.com/team113/messenger
    type: application
    urls:
    - https://team113.github.io/messenger/helm/messenger-0.1.4.tgz
    version: 0.1.4
  - annotations:
      artifacthub.io/license: AGPL-3.0-or-later
    apiVersion: v2
    appVersion: 0.1.0-alpha.13.5
    created: "2026-01-20T22:06:20.245183476Z"
    description: Open-source front-end part of messenger by team113.
    digest: da59b87ec3ae07a4a24a0939d775ae6a7168c5548f6105827e17b75779e608f0
    name: messenger
    sources:
    - https://github.com/team113/messenger
    type: application
    urls:
    - https://team113.github.io/messenger/helm/messenger-0.1.3.tgz
    version: 0.1.3
  - annotations:
      artifacthub.io/license: AGPL-3.0-or-later
    apiVersion: v2
    appVersion: 0.1.0-alpha.13.3
    created: "2026-01-20T22:06:20.243970939Z"
    description: Open-source front-end part of messenger by team113.
    digest: cd11914ba7919937912a5b3f8ad0fd710774f3f4c89dd61ff8c5c10e4ce4d01b
    name: messenger
    sources:
    - https://github.com/team113/messenger
    type: application
    urls:
    - https://team113.github.io/messenger/helm/messenger-0.1.2.tgz
    version: 0.1.2
  - annotations:
      artifacthub.io/license: AGPL-3.0-or-later
    apiVersion: v2
    appVersion: 0.1.0-alpha.11.1
    created: "2026-01-20T22:06:20.242964929Z"
    description: Open-source front-end part of messenger by team113.
    digest: 544d0a8623ffac5b1da3187125090a9e1c312871d7c7a50a35ef8ff416e5f053
    name: messenger
    sources:
    - https://github.com/team113/messenger
    type: application
    urls:
    - https://team113.github.io/messenger/helm/messenger-0.1.1.tgz
    version: 0.1.1
  - annotations:
      artifacthub.io/license: AGPL-3.0-or-later
    apiVersion: v2
    appVersion: 0.1.0-alpha.6
    created: "2026-01-20T22:06:20.242274979Z"
    description: Open-source front-end part of messenger by team113.
    digest: d4bb663eb57e582c699993c51eb6efe969ad2cc1e9b10d6ed2d90c861a0f6188
    name: messenger
    sources:
    - https://github.com/team113/messenger
    type: application
    urls:
    - https://team113.github.io/messenger/helm/messenger-0.1.0.tgz
    version: 0.1.0
  tapopa-messenger:
  - annotations:
      artifacthub.io/license: AGPL-3.0-or-later
    apiVersion: v2
    appVersion: 0.1.0
    created: "2026-01-20T22:06:20.247454101Z"
    description: Messenger by Tapopa.
    digest: d05cd1b1b72efcf353d446f9591d7df914fa5506bafdae3a08a1ea8822368722
    name: tapopa-messenger
    sources:
    - https://github.com/tapopa/messenger
    type: application
    urls:
    - https://team113.github.io/messenger/helm/tapopa-messenger-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-20T22:06:20.241102788Z"
