# Copyright © 2022-2025 IT ENGINEERING MANAGEMENT INC,
#                       <https://github.com/team113>
# Copyright © 2025 Ideas Networks Solutions S.A.,
#                       <https://github.com/tapopa>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License v3.0 as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License v3.0 for
# more details.
#
# You should have received a copy of the GNU Affero General Public License v3.0
# along with this program. If not, see
# <https://www.gnu.org/licenses/agpl-3.0.html>.

{{- if .Values.sftp.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ printf "%s-sftp" (include "tapopa-messenger.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "tapopa-messenger.chart" . | quote }}
    app.kubernetes.io/name: {{ include "tapopa-messenger.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/component: sftp
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "tapopa-messenger.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  ports:
    - name: sftp
      targetPort: sftp
      port: 22
    {{- with .Values.sftp.port }}
      nodePort: {{ . | int }}
    {{- end }}
      protocol: TCP
{{- end }}
