apiVersion: v2
name: tapopa-messenger
description: Messenger by Tapopa.
version: 0.1.0
appVersion: 0.1.0
type: application
sources:
  - https://github.com/tapopa/messenger
annotations:
  artifacthub.io/license: AGPL-3.0-or-later
